# Generated by Django 3.2.15 on 2022-11-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='Userid')),
                ('review', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=200)),
                ('product_id', models.IntegerField()),
                ('rating', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
