# Generated by Django 3.2.15 on 2022-11-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('stock', models.CharField(max_length=200)),
                ('shopid', models.IntegerField()),
                ('image', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
