# Generated by Django 3.2.15 on 2022-11-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('complaint', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('reply', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
    ]
