# Generated by Django 3.2.15 on 2022-11-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_holdername', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
