# Generated by Django 3.2.15 on 2022-11-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First Name', max_length=50)),
                ('last_name', models.CharField(db_column='Last Name', max_length=50)),
                ('username', models.CharField(db_column='Username', max_length=50)),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('place', models.CharField(db_column='Place', max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
            ],
            options={
                'db_table': 'registeration',
                'managed': False,
            },
        ),
    ]
